### PR TITLE
Realm 3 compatibility

### PR DESCRIPTION
**Pull request by skydivedan**
made changes that support Realm 3. It will not work on Realm 2.x and below.

### CODE REVIEW

**Comment by DenHeadless** [comment]
Hey! I will need to think how to release this, seems like major release is required because of API incompatibility. 

Can you use your branch for now?

**Comment by skydivedan** [comment]
Sure, no problem

**Comment by skydivedan** [comment]
Hey, sorry to pester, but will there be movement on this soon?

**Comment by DenHeadless** [comment]
Sorry, did not have time to take a look at this. I'm planning one more feature that requires major release as well, i was hoping to align them together with this feature to not make two major releases at once. I will try to do this this weekend or next one.

**Comment by DenHeadless** [comment]
Hey!

I've pushed [7.0.0-beta.1 release](https://github.com/DenHeadless/DTModelStorage/releases/tag/7.0.0-beta.1), including Realm 3.x syntax, thank you for contributing! 🍻

**Pull request closed without merging**
