### PR TITLE
- Update is not triggered if NSFRC reports move and source and destination paths are equal

### PR DESCRIPTION
**Pull request by pzbyszynski**

### CODE REVIEW

**Comment by DenHeadless** [comment]
Hi!

Can you describe when NSFRC sends you this message? I will probably merge this PR, because it should not harm anybody, however i'm really interested in why this is needed. 

What behaviour are you experiencing when this code is turned off?

**Comment by pzbyszynski** [comment]
@DenHeadless Please have a look at:
- http://www.openradar.me/22796598
- http://www.openradar.me/22380191

There seems to be a bug in NSFRC, after updating managed object NSFRC reports move where source and destination index are equal (instead of update). This leads to incorrect animations.

I get this error only on iOS 9 / Xcode 7.x

**Comment by DenHeadless** [comment]
Thanks! I've released DTModelStorage 1.3.3 with this fix.

**Comment by pzbyszynski** [comment]
Great, thanks a lot ;)

**Pull request merged**
